services:
  postgres:
    image: postgres:15
    container_name: prefect_postgres
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - prefect-db:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: >
      sh -c "
      mkdir -p /mlflow/artifacts &&
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts '*'
      "

  prefect:
    image: prefecthq/prefect:2.16.7-python3.12
    container_name: prefect_server
    restart: always
    command: >
      prefect server start
      --host 0.0.0.0
      --port 4200
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    ports:
      - "4200:4200"
    depends_on:
      - postgres

  prefect-worker:
    build: .
    container_name: prefect_worker
    restart: always
    working_dir: /app
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PYTHONPATH: /app
    command: >
      bash -c "
      sleep 10 &&
      prefect worker start --pool default-agent-pool --type process
      "
    volumes:
      - .:/app:rw
    depends_on:
      - prefect
      - mlflow

  ml_ops_app:
    build: .
    container_name: energy_mlops_container
    restart: always
    working_dir: /app
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PREFECT_API_URL: http://prefect:4200/api
      PYTHONPATH: /app
    depends_on:
      - mlflow
      - prefect
    stdin_open: true
    tty: true

  streamlit_ui:
    build: .
    container_name: energy_streamlit_ui
    restart: always
    working_dir: /app
    volumes:
      - .:/app:rw
    ports:
      - "8501:8501"
    environment:
      PYTHONPATH: /app
    command: >
      streamlit run ui/app.py
      --server.port=8501
      --server.address=0.0.0.0
    depends_on:
      - ml_ops_app

volumes:
  prefect-db: